### ISSUE TITLE
Review the Rebrickable data set -Allan

### ISSUE THREAD

**Issue by psftc** [falcontechnologies/wex-2024#2]
The data set used is from the Rebrickable website here [Rebrickable Downloads](https://rebrickable.com/downloads/). This issue has several steps to complete

Go to the downloads page above and identify the data files - we are interested only in the relational data and not the images. There should be 12 files, each of which ends with the file extension of '.gz'. Note the date of the files.
Download each of these files manually to your local machine.
Expand each file and review the data. You should look for the following things: header, number of columns, number of rows, types of data in the different columns, which columns are missing data
The download page has a model shown in a diagram. Review this given the data you've observed. When reviewing, consider mentally connecting theme, set, inventory, parts.
In this ticket, add several paragraphs about your observations which may include additional questions.

**Comment by atrieu1** [comment]
Colours:
4 columns, 268 rows
Begins with basic colours (blue, green, black, etc.)
Becomes more specific further down the dataset
No particular order in groupings
First colour is unknown

Question: What is an unknown colour? How is it unknown if there is an RGB value?

Elements:
4 columns, 89402 rows
Some design IDs missing
Further down the dataset design IDs are missing more frequently
Colour IDs often repeat certain numbers ex. 9999, 1004
Colour ID mostly grouped by number
Colour ID less organized further down the dataset
Part_num’s of each are numbers or numbers and letters
Letters of part_num appear in patterns i.e. 2277c01pr009 and 98603s02pr0021
Potentially a way to further categorize them

Question: What is the significance of a missing design ID

Inventories: 
3 columns, 38738 rows
Multiple set_num formats
months “-” then pair of numbers ex. Jan-22
Some with various starting digits “-” then 1 or two more digits ex. 40107-1
Some include names or letters, 
Assumption: meant to further categorize different sets under a theme
Some with fig “-” then 6 digits ex. Fig-006826
Used for Minifigures
Each has seemingly unique IDs
Some ID numbers are skipped over
Most are of version number 1, a handful with numbers greater than 1
Each change in version number occurs when pieces have the same set_num
Could suggest each version is an altered version of a certain set

Question: Why are some ID numbers skipped?

Inventory Minifigs:
3 columns, 21804 rows
Organized by inventory ID
Some numbers are skipped in inventory ID
Each fig-num is unique 
Most come in quantities of 1 but some are more

Inventory Parts:
6 columns, rows > 1048576
Part_num seems to contain similar part_nums to Inventories
Organized by inventory ID
Some numbers are skipped in inventory ID
Uses same colour ID system as element ID, but does not have the same organization
Some img_url’s missing
Implies a lack of images of certain pieces

Inventory Sets:
3 columns, 4432 rows
Organized by inventory_id
Uses some set_num formatting from Inventories, missing minifigures
Most have quantity of one, some with a couple more
Some have shared inventory_id but different set num
Could indicate that inventory_id denotes a theme with set_nums representing different sets within that theme

Minifigs:
4 columns,  14356 rows
Unique figure ids
Organized by figure id, numerically

Part Categories:
2 columns, 68 rows
Ordered by id, ascending numbers
Some missing id numbers
Very general name labels
Potentially their main categories of Lego

Part Relationship:
3 columns, 30989 rows
Rel_type letters are P, R, M, B, T, A
Rel_type, identified as letters, generally somewhat grouped up by letters
Parent_part_num always repeated at the beginning of the child_part_num
Question: What do each of the letters of the Rel_type mean?

Parts:
4 columns, 54498 rows
Organized by part_num, ascending numbers then switches to letters organized alphabetically
Parts of a set grouped up
Seems like the different patterns in part_nums are used to categorize each part into larger categories



Sets:
6 columns, 22680 rows
Organized by set_num, ascending numerical order
Theme_id used to show a general theme for each set
Ex. Ninjago, Legend of Chima and Starwars share theme_id 761
Some pieces have 0 num_parts

Themes:
3 columns, 461 rows
Organized by id, ascending numerical order
Various ones are missing parent_id
Assuming this means they are a main branch
Very general themes, seemingly represent all main themes lego has produced
