### ISSUE TITLE
Review the Rebrickable data set - Jayden

### ISSUE THREAD

**Issue by psftc** [falcontechnologies/wex-2024#4]
The data set used is from the Rebrickable website here [Rebrickable Downloads](https://rebrickable.com/downloads/). This issue has several steps to complete

Go to the downloads page above and identify the data files - we are interested only in the relational data and not the images. There should be 12 files, each of which ends with the file extension of '.gz'. Note the date of the files.
Download each of these files manually to your local machine.
Expand each file and review the data. You should look for the following things: header, number of columns, number of rows, types of data in the different columns, which columns are missing data
The download page has a model shown in a diagram. Review this given the data you've observed. When reviewing, consider mentally connecting theme, set, inventory, parts.
In this ticket, add several paragraphs about your observations which may include additional questions.

**Comment by jaydonos** [comment]
[WEX - Review of Rebrickable Data Set.pdf](https://github.com/falcontechnologies/wex-2024/files/15231057/WEX.-.Review.of.Rebrickable.Data.Set.pdf)
